- hosts: webservers
  tasks:
     - name: "Installing Apache Webserver"    
       package:
           name: "httpd"
           state: present


     - name: "Installing php software"
       package:
           name: "php"
           state: present

     - name: "Copy webpage"
       copy:
           dest: "/var/www/html/index.php"
           src: "index.php"

     - name: "start http server"
       service:
             name: "httpd"
             state: started

     - name: "Firewall Allow http service"
       firewalld:
             service: "http"
             immediate: yes
             state: enabled
             permanent: yes

- hosts: LB
  vars:
      - service_port: 8080
  tasks:
      - name: Installing Reverse proxy software""
        package:
            name: "haproxy"
            state: present

      - name: "Copying configuration file"
        template:
            src: "haproxy.cfg.j2"
            dest: "/etc/haproxy/haproxy.cfg"
        notify: "restart LB"

      - name: "allow LB port {{ service_port  }}"
        firewalld:
              port: "{{ service_port }}/tcp"
              permanent: yes
              immediate: yes
              state: enabled

  handlers:
      - name: "restart LB"
        service:
            name: "haproxy"
            state: restarted
            enabled: yes
